services:
  nginx:
    image: docker.guygubaby.top/nginx:stable-alpine
    container_name: freeaichat-2api-nginx
    restart: always
    environment:
      NGINX_PORT: "${NGINX_PORT:-4001}"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
    command: /bin/sh -c "envsubst '$$NGINX_PORT' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - app
    network_mode: host

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freeaichat-2api-app
    restart: unless-stopped
    env_file:
      - .env
    network_mode: host
